DROP DATABASE IF EXISTS restdb;
DROP USER IF EXISTS `restadmin`@`%`;
CREATE DATABASE IF NOT EXISTS restdb CHARACTER SET utf8nb4 COLLATE utf8nb4_unicode_ci;
CREATE USER IF NOT EXISTS `restadmin`@`%` IDENTIFIED WITH mysql_native_password BY  'password'
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW, VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `restdb`.* TO `restadmin`@`%`;